# -*- coding: utf-8 -*-
"""code9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cicnJNz0RGv0zS3GNUQNcpQuqAfnSTnc
"""

def cal_prod(a=2, b=6):
  print(a*b)


cal_prod()

fruits=["cat","dog","rabbit","elephant","rabbit"]

def print_len(list):
  print(len(list))

print_len(fruits)

